[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["Jesus Palacios <jesus.palacios@qredo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
faker = "^18.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
